export const productos = [
    'agitadores',
    'autoclaves',
    'cabina para lavado',
    'descremadoras',
    'empacadoras',
    'envasadoras',
    'equipos para lecheria y devivados',
    'equipos para procesar frutas',
    'equipos para procesar alimentos',
    'evaporadores',
    'formadoras de queso',
    'frezzers',
    'homogenizadores',
    'intercambiadores de calor',
    'lineas UHT',
    'mantequilleras',
    'marmitas de proceso',
    'mezcladores para solidos y polvos',
    'mixer - Emulsificadores',
    'molinos colidales',
    'pasteurizadores',
    'pulverizadores',
    'reactores',
    'silos para leche',
    'sistemas de bombeo',
    'soluciones para lavado CIP',
    'tanques',
    'tinas para queso',
    'yogurteras',
];
