export const productos = [
    'tinas',
    'mixers',
    'tanques',
    'frezzers',
    'batidoras',
    'mezcladoras',
    'envasadoras',
    'evaporadores',
    'descremadoras',
    'despulpadoras',
    'pasteurizadores',
    'homogenizadores',
    'esterilizadores',
    'desavorizadores',
    'mantequilleras',
    'lineas completas',
    'sistemas de lavado',
    'sistemas de bombeo',
    'moldeadoras y prensas',
    'trituradores y molinos',
    'empacadoras y embalaje',
    'servicios industriales',
    'agitacion y emulsificacion',
    'intercambiadoras para enfriamiento y calentamiento',
]