export const productos = [
    'tanques',
    'frezzers',
    'reactores',
    'agitadores',
    'lineas UHT',
    'yogurteras',
    'autoclaves',
    'envasadoras',
    'empacadoras',
    'evaporadores',
    'descremadoras',
    'mantequilleras',
    'pulverizadores',
    'homogenizadores',
    'pasteurizadores',
    'tinas para queso',
    'silos para leche',
    'molinos colidales',
    'sistemas de bombeo',
    'cabina para lavado',
    'formadoras de queso',
    'marmitas de proceso',
    'mixer / Emulsificadores',
    'intercambiadores de calor',
    'soluciones para lavado CIP',
    'equipos para procesar frutas',
    'mezcladores para solidos y polvos',
    'equipos para lecheria y devivados',
]